%Video : https://youtu.be/BeXXM24iFtk
%This is an autogenerated code


function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Apr-2021 06:57:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('Run','FontWeight','bold','FontName','Bookman Old Style');

% Create xlabel
xlabel('Over','FontWeight','bold','FontName','Bookman Old Style');

% Create title
title('Run Rate');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 20]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Bookman Old Style','FontSize',15,'FontWeight','bold');
